name: Workflow for Codecov example-python test
on: [push, pull_request]
jobs:
  codecov-report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create JSON file
      run: |
        mkdir -p /home/runner/work/
        echo '<?xml version="1.0" ?>
        <coverage branch-rate="1" line-rate="1" version="5.3">
            <packages>
                <package branch-rate="1" line-rate="1" name="example">
                    <classes>
                        <class branch-rate="1" line-rate="1" name="example.py">
                            <methods>
                                <method name="add" hits="2" branch="false" />
                                <method name="subtract" hits="2" branch="false" />
                            </methods>
                            <lines>
                                <line number="1" hits="1" />
                                <line number="2" hits="1" />
                                <line number="3" hits="1" />
                                <line number="4" hits="1" />
                            </lines>
                        </class>
                    </classes>
                </package>
            </packages>
        </coverage>' > /home/runner/work/coverage.xml

    - name: Verify file content
      run: cat /home/runner/work/coverage.xml

    - uses: codecov/codecov-action@v4
      #    - name: Download Codecov CLI
      #      run: |
      #        curl -Os https://cli.codecov.io/latest/linux/codecov
      #        chmod +x codecov
      #        ./codecov --help

      #    - name: Upload report to Codecov
      #      run: ./codecov -u https://codecov-gateway.reydixdev.com upload-process -f /home/runner/work/coverage.json -t ${{ secrets.CODECOV_TOKEN }} -v

      with:
        file: /home/runner/work/coverage.xml
        verbose: true
        url: https://codecov.reydixdev.com
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
